config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :subscriptions
  resources :services
  resources :customers
  resources :customer_services
  resources :partners
 
    
 devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations" }
 
 

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :customer
  belongs_to :service
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
    
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
    @customers = Customer.all
    @services = Service.all
  end

  # GET /subscriptions/1/edit
  def edit
    @customers = Customer.all
    @services = Service.all
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:customer_id, :service_id, :subscription_start, :subscription_end)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= simple_form_for(@subscription) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.label :customer_id %><br />
    <%= collection_select(:subscription, :customer_id, @customers, :id, :name, {:prompt => false}) %><br />
    <%= f.label :service_id %><br />
    <%= collection_select(:subscription, :service_id, @services, :id, :name, {:prompt => false}) %>
    <%= f.input :subscription_start %>
    <%= f.input :subscription_end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>
      Editing <small><%= link_to subscription,  @subscription %></small>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "Subscriptions", subscriptions_path %></li>
        <li class="active">Edit</li>
      </ol>
    </h1>
  </section>
<% end %>

<%= render 'form' %>

app/views/subscriptions/index.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Listing <small>subscriptions</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">subscriptions</li>
    </ol>    
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to new_subscription_path(@subscription), :class => 'btn btn-success' do %>
              <span class="glyphicon glyphicon-plus"></span>
              New Subscription
            <% end %>          
          </div>
        </div>
        <div class="box-body table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
              <th>Customer</th>
              <th>Service</th>
              <th>Subscription start</th>
              <th>Subscription end</th>
                            <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <%= content_tag_for(:tr, @subscriptions) do |subscription| %>
              <td><%= subscription.customer_id %></td>
              <td><%= subscription.service_id %></td>
              <td><%= subscription.subscription_start %></td>
              <td><%= subscription.subscription_end %></td>
                            <td><%= link_to 'Show', subscription %></td>
                <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
                <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/subscriptions/new.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>New <small>subscription</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "subscriptions", subscriptions_path %></li>
      <li class="active">New</li>
    </ol>
  </section>
<% end %>

<%= render 'form' %>

app/views/subscriptions/show.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Show <small>subscription</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "Subscriptions", subscriptions_path %></li>
      <li class="active">Show</li>
    </ol>
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-md-10">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to edit_subscription_path(@subscription), :class => 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
            <% end %>          
          </div>
        </div>
        <div class="box-body">
          <dl class="dl-horizontal">
            <dt>Customer:</dt>
            <dd><%= @subscription.customer.name %></dd>

            <dt>Service:</dt>
            <dd><%= @subscription.service.name %></dd>

            <dt>Subscription start:</dt>
            <dd><%= @subscription.subscription_start %></dd>

            <dt>Subscription end:</dt>
            <dd><%= @subscription.subscription_end %></dd>

          </dl>
        </div>
      </div>
    </div>
  </div>
</section>