config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :subscriptions
  resources :services
  resources :customers
  resources :customer_services
  resources :partners
 
    
 devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations" }
 
 

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    @subscriptions = Subscription.all
  end

  # GET /payments/1/edit
  def edit
    @subscriptions = Subscription.all
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:subscription_id, :amount, :date_paid)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= simple_form_for(@payment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
<%= f.label :customer_id %><br />
    <%= collection_select(:payment, :subscription_id, @subscriptions, :id, :customer_id, {:prompt => false}) %><br />
    <%= f.input :amount %>
    <%= f.input :date_paid %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>
      Editing <small><%= link_to payment,  @payment %></small>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "Payments", payments_path %></li>
        <li class="active">Edit</li>
      </ol>
    </h1>
  </section>
<% end %>

<%= render 'form' %>

app/views/payments/index.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Listing <small>payments</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">payments</li>
    </ol>    
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to new_payment_path(@payment), :class => 'btn btn-success' do %>
              <span class="glyphicon glyphicon-plus"></span>
              New Payment
            <% end %>          
          </div>
        </div>
        <div class="box-body table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
              <th>Subscription</th>
              <th>Amount</th>
              <th>Date paid</th>
                            <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <%= content_tag_for(:tr, @payments) do |payment| %>
              <td><%= payment.subscription_id %></td>
              <td><%= payment.amount %></td>
              <td><%= payment.date_paid %></td>
                            <td><%= link_to 'Show', payment %></td>
                <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
                <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/payments/new.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>New <small>payment</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "payments", payments_path %></li>
      <li class="active">New</li>
    </ol>
  </section>
<% end %>

<%= render 'form' %>

app/views/payments/show.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Show <small>payment</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "Payments", payments_path %></li>
      <li class="active">Show</li>
    </ol>
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to edit_payment_path(@payment), :class => 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
            <% end %>          
          </div>
        </div>
        <div class="box-body">
          <dl class="dl-horizontal">
            <dt>Subscription:</dt>
            <dd><%= @payment.subscription_id %></dd>

            <dt>Amount:</dt>
            <dd><%= @payment.amount %></dd>

            <dt>Date paid:</dt>
            <dd><%= @payment.date_paid %></dd>

          </dl>
        </div>
      </div>
    </div>
  </div>
</section>