config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :subscriptions
  resources :services
  resources :customers
  resources :customer_services
  resources :partners
 
    
 devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations" }
 
 

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer_service.rb
class CustomerService < ApplicationRecord
  belongs_to :customer
  belongs_to :service
end

app/controllers/customer_services_controller.rb
class CustomerServicesController < ApplicationController
  before_action :set_customer_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /customer_services
  # GET /customer_services.json
  def index
    @customer_services = CustomerService.all
  end

  # GET /customer_services/1
  # GET /customer_services/1.json
  def show
  end

  # GET /customer_services/new
  def new
    @customer_service = CustomerService.new
  end

  # GET /customer_services/1/edit
  def edit
  end

  # POST /customer_services
  # POST /customer_services.json
  def create
    @customer_service = CustomerService.new(customer_service_params)

    respond_to do |format|
      if @customer_service.save
        format.html { redirect_to @customer_service, notice: 'Customer service was successfully created.' }
        format.json { render :show, status: :created, location: @customer_service }
      else
        format.html { render :new }
        format.json { render json: @customer_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_services/1
  # PATCH/PUT /customer_services/1.json
  def update
    respond_to do |format|
      if @customer_service.update(customer_service_params)
        format.html { redirect_to @customer_service, notice: 'Customer service was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_service }
      else
        format.html { render :edit }
        format.json { render json: @customer_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_services/1
  # DELETE /customer_services/1.json
  def destroy
    @customer_service.destroy
    respond_to do |format|
      format.html { redirect_to customer_services_url, notice: 'Customer service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_service
      @customer_service = CustomerService.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_service_params
      params.require(:customer_service).permit(:customer_id, :service_id, :customer_id, :service_id)
    end
end

app/helpers/customer_services_helper.rb
module CustomerServicesHelper
end

app/views/customer_services/_form.html.erb
<%= simple_form_for(@customer_service) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    
    <%= f.association :customer %>
    <%= f.association :service %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/customer_services/edit.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>
      Editing <small><%= link_to edit_customer_service_path,  @customer_service %></small>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "Customer_services", customer_services_path %></li>
        <li class="active">Edit</li>
      </ol>
    </h1>
  </section>
<% end %>

<%= render 'form' %>

app/views/customer_services/index.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Listing <small>customer_services</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">customer_services</li>
    </ol>    
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to new_customer_service_path(@customer_service), :class => 'btn btn-success' do %>
              <span class="glyphicon glyphicon-plus"></span>
              New Customer service
            <% end %>          
          </div>
        </div>
        <div class="box-body table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
              <th>Customer</th>
              <th>Service</th>
           
                            <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <%= content_tag_for(:tr, @customer_services) do |customer_service| %>
            
              <td><%= customer_service.customer.name %></td>
              <td><%= customer_service.service.name %></td>
                            <td><%= link_to 'Show', customer_service %></td>
                <td><%= link_to 'Edit', edit_customer_service_path(customer_service) %></td>
                <td><%= link_to 'Destroy', customer_service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/customer_services/new.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>New <small>customer_service</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "customer_services", customer_services_path %></li>
      <li class="active">New</li>
    </ol>
  </section>
<% end %>

<%= render 'form' %>

app/views/customer_services/show.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Show <small>customer_service</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "Customer_services", customer_services_path %></li>
      <li class="active">Show</li>
    </ol>
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to edit_customer_service_path(@customer_service), :class => 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
            <% end %>          
          </div>
        </div>
        <div class="box-body">
          <dl class="dl-horizontal">
            

            <dt>Customer:</dt>
            <dd><%= @customer_service.customer.name %></dd>

            <dt>Service:</dt>
            <dd><%= @customer_service.service.name %></dd>

          </dl>
        </div>
      </div>
    </div>
  </div>
</section>