config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :subscriptions
  resources :services
  resources :customers
  resources :customer_services
  resources :partners
 
    
 devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations" }
 
 

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :subscriptions
end

app/models/customer_service.rb
class CustomerService < ApplicationRecord
  belongs_to :customer
  belongs_to :service
end

app/models/partner.rb
class Partner < ApplicationRecord
  belongs_to :customer
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :subscriptions
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :customer
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :customers
         has_many :services
         has_many :assign_services
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :authenticate_user!

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
layout "empty"
  def index
	if signed_in? 
  		redirect_to   home_index_path
  	end
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /partners
  # GET /partners.json
  def index
    @partners = Partner.all
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
  end

  # GET /partners/new
  def new
    @partner = Partner.new
  end

  # GET /partners/1/edit
  def edit
  end

  # POST /partners
  # POST /partners.json
  def create
    @partner = Partner.new(partner_params)

    respond_to do |format|
      if @partner.save
        format.html { redirect_to @partner, notice: 'Partner was successfully created.' }
        format.json { render :show, status: :created, location: @partner }
      else
        format.html { render :new }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1
  # PATCH/PUT /partners/1.json
  def update
    respond_to do |format|
      if @partner.update(partner_params)
        format.html { redirect_to @partner, notice: 'Partner was successfully updated.' }
        format.json { render :show, status: :ok, location: @partner }
      else
        format.html { render :edit }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy
    @partner.destroy
    respond_to do |format|
      format.html { redirect_to partners_url, notice: 'Partner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner
      @partner = Partner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partner_params
      params.require(:partner).permit(:name, :customer_type, :pan_number, :aadhaar_number, :voter_id_number, :mobile_number, :alternate_mobile_number, :date_of_birth, :bank_name, :bank_ac_number, :bank_branch, :customer_id)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    @subscriptions = Subscription.all
  end

  # GET /payments/1/edit
  def edit
    @subscriptions = Subscription.all
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:subscription_id, :amount, :date_paid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nav_helper.rb
module NavHelper
  def nav_link(page, &link_text) 
    class_name = request.env['PATH_INFO'].match(page) ? 'active' : nil

    content_tag(:li, class: class_name) do
      link_to page do
        link_text.call
      end
    end
  end

  def treeview_link(text, &links)
    content = link_to('#') do
      content_tag(:span, text) <<
      content_tag(:i, '', class: "fa pull-right fa-angle-left")
    end

    content << content_tag(:ul, class: 'treeview-menu') do 
      links.call
    end

    content_tag :li, class: 'treeview' do
      content
    end
  end
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/_application_header.html.erb
<header class="header">
  <a href="#" class="logo">
    <!-- Add the class icon to your logo image or logo icon to add the margining -->
    Purple
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <div class="navbar-right">
      <ul class="nav navbar-nav">
        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope"></i>
            <span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 4 messages</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li><!-- start message -->
                  <a href="#">
                    <div class="pull-left">
                      <img src="/img/avatar3.png" class="img-circle" alt="User Image"/>
                    </div>
                    <h4>
                      Support Team
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li><!-- end message -->
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="/img/avatar2.png" class="img-circle" alt="user image"/>
                    </div>
                    <h4>
                      AdminLTE Design Team
                      <small><i class="fa fa-clock-o"></i> 2 hours</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="/img/avatar.png" class="img-circle" alt="user image"/>
                    </div>
                    <h4>
                      Developers
                      <small><i class="fa fa-clock-o"></i> Today</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="/img/avatar2.png" class="img-circle" alt="user image"/>
                    </div>
                    <h4>
                      Sales Department
                      <small><i class="fa fa-clock-o"></i> Yesterday</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="/img/avatar.png" class="img-circle" alt="user image"/>
                    </div>
                    <h4>
                      Reviewers
                      <small><i class="fa fa-clock-o"></i> 2 days</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
          </ul>
        </li>
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="glyphicon glyphicon-user"></i>
            <span>Jane Doe <i class="caret"></i></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header bg-light-blue">
              <img src="/img/avatar3.png" class="img-circle" alt="User Image" />
              <p>
                Jane Doe - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
              </div>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="#" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_application_sidebar.html.erb
<section class="sidebar">
  <!-- Sidebar user panel -->
  <div class="user-panel">
    <div class="pull-left image">
      <img src="/img/avatar3.png" class="img-circle" alt="User Image" />
    </div>
    <div class="pull-left info">
      <p>Hello, Jane</p>

      <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      
    </div>
  </div>
  <!-- search form -->
  <form action="#" method="get" class="sidebar-form">
    <div class="input-group">
      <input type="text" name="q" class="form-control" placeholder="Search..."/>
      <span class="input-group-btn">
        <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
      </span>
    </div>
  </form>
  <!-- /.search form -->
  <!-- sidebar menu: : style can be found in sidebar.less -->
  <ul class="sidebar-menu">
    <%= nav_link root_path do %>
      <i class="fa fa-dashboard"></i> <span>Dashboard</span>
    <% end %>
     <%= nav_link customers_path do %>
      <i class="fa fa-users"></i> <span>Customers</span>
    <% end %>
     <%= nav_link partners_path do %>
      <i class="fa fa-user"></i> <span>Partners</span>
    <% end %>
     <%= nav_link services_path do %>
      <i class="fa fa-tasks"></i> <span>Services</span>
    <% end %>
    <%= nav_link subscriptions_path do %>
      <i class="fa fa-sign-in"></i> <span>Subscriptions</span>
    <% end %>
     <%= nav_link payments_path do %>
      <i class="fa fa-money"></i> <span>Payments</span>
    <% end %>
  </ul>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <meta name="description" content="">
  <meta name="author" content="">
  <title>AdminLTE::Dashboard</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="skin-blue">

  <%= render "layouts/application_header" %>

  <div class="wrapper row-offcanvas row-offcanvas-left">
    <aside class="left-side sidebar-offcanvas">
      <%= render "layouts/application_sidebar" %>
    </aside>
    <aside class="right-side">
      <%= yield(:content_header) %>

      <% flash.each do |name, msg| %>
        <div class="pad margin no-print">
          <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <%= msg %>
          <% end %>
        </div>
      <% end %>
<div class="container">

      <%= yield %>

      </div>
    </aside>
  </div>

  <div class="spinner no-print hidden">
    <img src="/img/ajax-loader.gif" alt="">
  </div>

</body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <meta name="description" content="">
  <meta name="author" content="">
  <title>AdminLTE::sing</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="skin-blue">

  <%# render "layouts/application_header" %>

  <div class="wrapper row-offcanvas row-offcanvas-left">
     
     <div class="container">
    
      <%= yield(:content_header) %>

      <% flash.each do |name, msg| %>
        <div class="pad margin no-print">
          <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <%= msg %>
          <% end %>
        </div>
      <% end %>

      <%= yield %>
   </div>
  </div>

  <div class="spinner no-print hidden">
    <img src="/img/ajax-loader.gif" alt="">
  </div>

</body>
</html>